const console = require('console');
var encoder = require('../coder/js/tpl/DopEncode');
var binary = new encoder();
binary.writeChar(10);
console.log(binary.write_pos);
binary.writeChar(20);
console.log(binary.write_pos);
binary.writeChar(30);
console.log(binary.write_pos);
binary.writeChar(40);
console.log(binary.write_pos);
binary.writeShort(0xfff);
console.log(binary.write_pos);
binary.writeInt(0xffff);
console.log(binary.write_pos);
binary.writeBigInt(0xffffffff);
console.log(binary.write_pos);
binary.writeString('Hello');
console.log(binary.write_pos);
binary.writeFloat(100.100);
console.log(binary.write_pos);
binary.writeDouble(1009.1001);
console.log(binary.write_pos);
